cc_binary(
    name = 'routersvr',
    srcs = [
       'main.cpp',
       'router_svr.cpp',
    ],
    deps = [
        '//commonlib:common',
		'//protolib:proto',
		'//hiredis_wrapper:hiredis_wrapper',
		'//slience:slience'
    ],
)
