cc_binary(
    name = 'routersvr',
    srcs = [
      # 'main.cpp',
      # 'router_svr.cpp',
	   'all_src.cpp'
    ],
    deps = [
        '//commonlib:common',
		'//protolib:proto',
		'//hiredis_wrapper:hiredis_wrapper',
		'//slience:slience'
    ],
)
