
#proto_library(
#)

cc_library(
    name = 'common',
    srcs = [
	   'svr_base/ApplicationBase.cpp',
	   'svr_base/ApplicationFunc.cpp'
    ],

    deps = [
		'//slience:slience',
		'#pthread',
		'#mysqlcppconn'
    ],

    #link_all_symbols = True,
)


