
#proto_library(
#)

cc_library(
    name = 'sliencelib',
    srcs = [
	   'base/buffer.cpp',
	   'base/condition.cpp',
	   'base/mutexlock.cpp',
	   'base/logger.cpp',
    ],

    deps = [
		'#pthread',
    ],

    #link_all_symbols = True,
)


