// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: routersvr_config.proto

#ifndef PROTOBUF_routersvr_5fconfig_2eproto__INCLUDED
#define PROTOBUF_routersvr_5fconfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_routersvr_5fconfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsRouterSvrConfigImpl();
void InitDefaultsRouterSvrConfig();
inline void InitDefaults() {
  InitDefaultsRouterSvrConfig();
}
}  // namespace protobuf_routersvr_5fconfig_2eproto
namespace config {
class RouterSvrConfig;
class RouterSvrConfigDefaultTypeInternal;
extern RouterSvrConfigDefaultTypeInternal _RouterSvrConfig_default_instance_;
}  // namespace config
namespace config {

// ===================================================================

class RouterSvrConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:config.RouterSvrConfig) */ {
 public:
  RouterSvrConfig();
  virtual ~RouterSvrConfig();

  RouterSvrConfig(const RouterSvrConfig& from);

  inline RouterSvrConfig& operator=(const RouterSvrConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RouterSvrConfig(RouterSvrConfig&& from) noexcept
    : RouterSvrConfig() {
    *this = ::std::move(from);
  }

  inline RouterSvrConfig& operator=(RouterSvrConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RouterSvrConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RouterSvrConfig* internal_default_instance() {
    return reinterpret_cast<const RouterSvrConfig*>(
               &_RouterSvrConfig_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RouterSvrConfig* other);
  friend void swap(RouterSvrConfig& a, RouterSvrConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RouterSvrConfig* New() const PROTOBUF_FINAL { return New(NULL); }

  RouterSvrConfig* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RouterSvrConfig& from);
  void MergeFrom(const RouterSvrConfig& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RouterSvrConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 log_level = 1;
  bool has_log_level() const;
  void clear_log_level();
  static const int kLogLevelFieldNumber = 1;
  ::google::protobuf::int32 log_level() const;
  void set_log_level(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:config.RouterSvrConfig)
 private:
  void set_has_log_level();
  void clear_has_log_level();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 log_level_;
  friend struct ::protobuf_routersvr_5fconfig_2eproto::TableStruct;
  friend void ::protobuf_routersvr_5fconfig_2eproto::InitDefaultsRouterSvrConfigImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RouterSvrConfig

// optional int32 log_level = 1;
inline bool RouterSvrConfig::has_log_level() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RouterSvrConfig::set_has_log_level() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RouterSvrConfig::clear_has_log_level() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RouterSvrConfig::clear_log_level() {
  log_level_ = 0;
  clear_has_log_level();
}
inline ::google::protobuf::int32 RouterSvrConfig::log_level() const {
  // @@protoc_insertion_point(field_get:config.RouterSvrConfig.log_level)
  return log_level_;
}
inline void RouterSvrConfig::set_log_level(::google::protobuf::int32 value) {
  set_has_log_level();
  log_level_ = value;
  // @@protoc_insertion_point(field_set:config.RouterSvrConfig.log_level)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace config

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_routersvr_5fconfig_2eproto__INCLUDED
