// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: svr_base.proto

#include "svr_base.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace proto {
class SocketClientInDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SocketClientIn>
      _instance;
} _SocketClientIn_default_instance_;
class SocketClientOutDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SocketClientOut>
      _instance;
} _SocketClientOut_default_instance_;
}  // namespace proto
namespace protobuf_svr_5fbase_2eproto {
void InitDefaultsSocketClientInImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::proto::_SocketClientIn_default_instance_;
    new (ptr) ::proto::SocketClientIn();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::SocketClientIn::InitAsDefaultInstance();
}

void InitDefaultsSocketClientIn() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSocketClientInImpl);
}

void InitDefaultsSocketClientOutImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::proto::_SocketClientOut_default_instance_;
    new (ptr) ::proto::SocketClientOut();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::SocketClientOut::InitAsDefaultInstance();
}

void InitDefaultsSocketClientOut() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSocketClientOutImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::SocketClientIn, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::SocketClientIn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::SocketClientOut, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::SocketClientOut, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 5, sizeof(::proto::SocketClientIn)},
  { 5, 10, sizeof(::proto::SocketClientOut)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_SocketClientIn_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_SocketClientOut_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "svr_base.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016svr_base.proto\022\005proto\"\020\n\016SocketClientI"
      "n\"\021\n\017SocketClientOut"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 60);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "svr_base.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_svr_5fbase_2eproto
namespace proto {

// ===================================================================

void SocketClientIn::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SocketClientIn::SocketClientIn()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_svr_5fbase_2eproto::InitDefaultsSocketClientIn();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.SocketClientIn)
}
SocketClientIn::SocketClientIn(const SocketClientIn& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:proto.SocketClientIn)
}

void SocketClientIn::SharedCtor() {
  _cached_size_ = 0;
}

SocketClientIn::~SocketClientIn() {
  // @@protoc_insertion_point(destructor:proto.SocketClientIn)
  SharedDtor();
}

void SocketClientIn::SharedDtor() {
}

void SocketClientIn::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SocketClientIn::descriptor() {
  ::protobuf_svr_5fbase_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_svr_5fbase_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SocketClientIn& SocketClientIn::default_instance() {
  ::protobuf_svr_5fbase_2eproto::InitDefaultsSocketClientIn();
  return *internal_default_instance();
}

SocketClientIn* SocketClientIn::New(::google::protobuf::Arena* arena) const {
  SocketClientIn* n = new SocketClientIn;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SocketClientIn::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SocketClientIn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SocketClientIn::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.SocketClientIn)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:proto.SocketClientIn)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.SocketClientIn)
  return false;
#undef DO_
}

void SocketClientIn::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.SocketClientIn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.SocketClientIn)
}

::google::protobuf::uint8* SocketClientIn::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.SocketClientIn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SocketClientIn)
  return target;
}

size_t SocketClientIn::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.SocketClientIn)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SocketClientIn::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.SocketClientIn)
  GOOGLE_DCHECK_NE(&from, this);
  const SocketClientIn* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SocketClientIn>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.SocketClientIn)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.SocketClientIn)
    MergeFrom(*source);
  }
}

void SocketClientIn::MergeFrom(const SocketClientIn& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.SocketClientIn)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void SocketClientIn::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.SocketClientIn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SocketClientIn::CopyFrom(const SocketClientIn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.SocketClientIn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SocketClientIn::IsInitialized() const {
  return true;
}

void SocketClientIn::Swap(SocketClientIn* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SocketClientIn::InternalSwap(SocketClientIn* other) {
  using std::swap;
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SocketClientIn::GetMetadata() const {
  protobuf_svr_5fbase_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_svr_5fbase_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SocketClientOut::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SocketClientOut::SocketClientOut()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_svr_5fbase_2eproto::InitDefaultsSocketClientOut();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.SocketClientOut)
}
SocketClientOut::SocketClientOut(const SocketClientOut& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:proto.SocketClientOut)
}

void SocketClientOut::SharedCtor() {
  _cached_size_ = 0;
}

SocketClientOut::~SocketClientOut() {
  // @@protoc_insertion_point(destructor:proto.SocketClientOut)
  SharedDtor();
}

void SocketClientOut::SharedDtor() {
}

void SocketClientOut::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SocketClientOut::descriptor() {
  ::protobuf_svr_5fbase_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_svr_5fbase_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SocketClientOut& SocketClientOut::default_instance() {
  ::protobuf_svr_5fbase_2eproto::InitDefaultsSocketClientOut();
  return *internal_default_instance();
}

SocketClientOut* SocketClientOut::New(::google::protobuf::Arena* arena) const {
  SocketClientOut* n = new SocketClientOut;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SocketClientOut::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SocketClientOut)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SocketClientOut::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.SocketClientOut)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:proto.SocketClientOut)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.SocketClientOut)
  return false;
#undef DO_
}

void SocketClientOut::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.SocketClientOut)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.SocketClientOut)
}

::google::protobuf::uint8* SocketClientOut::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.SocketClientOut)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SocketClientOut)
  return target;
}

size_t SocketClientOut::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.SocketClientOut)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SocketClientOut::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.SocketClientOut)
  GOOGLE_DCHECK_NE(&from, this);
  const SocketClientOut* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SocketClientOut>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.SocketClientOut)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.SocketClientOut)
    MergeFrom(*source);
  }
}

void SocketClientOut::MergeFrom(const SocketClientOut& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.SocketClientOut)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void SocketClientOut::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.SocketClientOut)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SocketClientOut::CopyFrom(const SocketClientOut& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.SocketClientOut)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SocketClientOut::IsInitialized() const {
  return true;
}

void SocketClientOut::Swap(SocketClientOut* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SocketClientOut::InternalSwap(SocketClientOut* other) {
  using std::swap;
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SocketClientOut::GetMetadata() const {
  protobuf_svr_5fbase_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_svr_5fbase_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto

// @@protoc_insertion_point(global_scope)
