// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: svr_base.proto

#ifndef PROTOBUF_svr_5fbase_2eproto__INCLUDED
#define PROTOBUF_svr_5fbase_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_svr_5fbase_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSocketClientInImpl();
void InitDefaultsSocketClientIn();
void InitDefaultsSocketClientOutImpl();
void InitDefaultsSocketClientOut();
inline void InitDefaults() {
  InitDefaultsSocketClientIn();
  InitDefaultsSocketClientOut();
}
}  // namespace protobuf_svr_5fbase_2eproto
namespace proto {
class SocketClientIn;
class SocketClientInDefaultTypeInternal;
extern SocketClientInDefaultTypeInternal _SocketClientIn_default_instance_;
class SocketClientOut;
class SocketClientOutDefaultTypeInternal;
extern SocketClientOutDefaultTypeInternal _SocketClientOut_default_instance_;
}  // namespace proto
namespace proto {

// ===================================================================

class SocketClientIn : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.SocketClientIn) */ {
 public:
  SocketClientIn();
  virtual ~SocketClientIn();

  SocketClientIn(const SocketClientIn& from);

  inline SocketClientIn& operator=(const SocketClientIn& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SocketClientIn(SocketClientIn&& from) noexcept
    : SocketClientIn() {
    *this = ::std::move(from);
  }

  inline SocketClientIn& operator=(SocketClientIn&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SocketClientIn& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SocketClientIn* internal_default_instance() {
    return reinterpret_cast<const SocketClientIn*>(
               &_SocketClientIn_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SocketClientIn* other);
  friend void swap(SocketClientIn& a, SocketClientIn& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SocketClientIn* New() const PROTOBUF_FINAL { return New(NULL); }

  SocketClientIn* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SocketClientIn& from);
  void MergeFrom(const SocketClientIn& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SocketClientIn* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto.SocketClientIn)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  friend struct ::protobuf_svr_5fbase_2eproto::TableStruct;
  friend void ::protobuf_svr_5fbase_2eproto::InitDefaultsSocketClientInImpl();
};
// -------------------------------------------------------------------

class SocketClientOut : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.SocketClientOut) */ {
 public:
  SocketClientOut();
  virtual ~SocketClientOut();

  SocketClientOut(const SocketClientOut& from);

  inline SocketClientOut& operator=(const SocketClientOut& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SocketClientOut(SocketClientOut&& from) noexcept
    : SocketClientOut() {
    *this = ::std::move(from);
  }

  inline SocketClientOut& operator=(SocketClientOut&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SocketClientOut& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SocketClientOut* internal_default_instance() {
    return reinterpret_cast<const SocketClientOut*>(
               &_SocketClientOut_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SocketClientOut* other);
  friend void swap(SocketClientOut& a, SocketClientOut& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SocketClientOut* New() const PROTOBUF_FINAL { return New(NULL); }

  SocketClientOut* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SocketClientOut& from);
  void MergeFrom(const SocketClientOut& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SocketClientOut* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto.SocketClientOut)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  friend struct ::protobuf_svr_5fbase_2eproto::TableStruct;
  friend void ::protobuf_svr_5fbase_2eproto::InitDefaultsSocketClientOutImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SocketClientIn

// -------------------------------------------------------------------

// SocketClientOut

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_svr_5fbase_2eproto__INCLUDED
